import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";

const execFileAsync =
  promisify(execFile);

const GITHUB_REPO =
  "git@github.com:DoanGiaHuyVu/nene-build.git";

const GITHUB_WEB_REPO =
  "https://github.com/DoanGiaHuyVu/nene-build";

const SSH_KEY =
  "/home/nene/.ssh/nene_github";

const PUBLISH_IGNORE =
  "/home/nene/ne-ne/publish.gitignore";

async function git(
  cwd: string,
  args: string[]
) {
  return execFileAsync(
    "git",
    args,
    {
      cwd,
      env: {
        ...process.env,
        GIT_SSH_COMMAND:
          `ssh -i ${SSH_KEY} -o IdentitiesOnly=yes`,
      },
    }
  );
}

export type GithubPublishResult = {
  branch: string;
  url: string;
  commit: string;
};

type PublishOptions = {
  branch?: string;
  commitMessage?: string;
};

async function configureRepo(
  repoDir: string
) {
  await git(repoDir, [
    "config",
    "user.name",
    "ne-ne",
  ]);

  await git(repoDir, [
    "config",
    "user.email",
    "nene-agent@users.noreply.github.com",
  ]);

  const gitInfoDir =
    path.join(
      repoDir,
      ".git",
      "info"
    );

  await fs.mkdir(
    gitInfoDir,
    {
      recursive: true,
    }
  );

  const ignoreContents =
    await fs.readFile(
      PUBLISH_IGNORE,
      "utf8"
    );

  await fs.writeFile(
    path.join(
      gitInfoDir,
      "exclude"
    ),
    ignoreContents
  );
}

async function replaceWorktree(
  artifactDir: string,
  repoDir: string
) {
  /*
   * Remove the previous checked-out project,
   * but keep Git history.
   */
  const oldEntries =
    await fs.readdir(repoDir);

  for (const entry of oldEntries) {
    if (entry === ".git") {
      continue;
    }

    await fs.rm(
      path.join(
        repoDir,
        entry
      ),
      {
        recursive: true,
        force: true,
      }
    );
  }

  /*
   * Copy the newly generated artifact
   * into the existing repository.
   */
  const newEntries =
    await fs.readdir(
      artifactDir
    );

  for (const entry of newEntries) {
    if (entry === ".git") {
      continue;
    }

    await fs.cp(
      path.join(
        artifactDir,
        entry
      ),
      path.join(
        repoDir,
        entry
      ),
      {
        recursive: true,
        force: true,
      }
    );
  }
}

export async function publishArtifactToGithub(
  taskId: string,
  artifactDir: string,
  options: PublishOptions = {}
): Promise<GithubPublishResult> {
  const shortId =
    taskId.slice(0, 8);

  /*
   * Initial build:
   * create task/<original-id>.
   *
   * Continuation:
   * reuse the existing branch.
   */
  const branch =
    options.branch ??
    `task/${shortId}`;

  await fs.access(
    artifactDir
  );

  /*
   * Never trust a .git directory
   * produced inside the sandbox.
   */
  await fs.rm(
    path.join(
      artifactDir,
      ".git"
    ),
    {
      recursive: true,
      force: true,
    }
  );

  const tempRoot =
    await fs.mkdtemp(
      "/tmp/nene-github-"
    );

  const repoDir =
    path.join(
      tempRoot,
      "repo"
    );

  try {
    if (options.branch) {
      /*
       * CONTINUATION:
       *
       * Clone the existing branch so the
       * previous commit becomes the parent
       * of the new commit.
       */
      await git(
        tempRoot,
        [
          "clone",
          "--branch",
          branch,
          "--single-branch",
          GITHUB_REPO,
          repoDir,
        ]
      );
    } else {
      /*
       * INITIAL PROJECT:
       *
       * Start a new repository/branch.
       */
      await fs.mkdir(
        repoDir,
        {
          recursive: true,
        }
      );

      await git(
        repoDir,
        [
          "init",
        ]
      );

      await git(
        repoDir,
        [
          "checkout",
          "-B",
          branch,
        ]
      );

      await git(
        repoDir,
        [
          "remote",
          "add",
          "origin",
          GITHUB_REPO,
        ]
      );
    }

    await configureRepo(
      repoDir
    );

    await replaceWorktree(
      artifactDir,
      repoDir
    );

    await git(
      repoDir,
      [
        "add",
        "-A",
      ]
    );

    const {
      stdout: status,
    } =
      await git(
        repoDir,
        [
          "status",
          "--porcelain",
        ]
      );

    /*
     * A no-op continuation is allowed.
     */
    if (status.trim()) {
      await git(
        repoDir,
        [
          "commit",
          "-m",
          options.commitMessage ??
            `Build generated by ne-ne (${shortId})`,
        ]
      );
    }

    /*
     * Crucially:
     *
     * NO --force here.
     *
     * Continuations extend Git history.
     */
    await git(
      repoDir,
      [
        "push",
        "-u",
        "origin",
        branch,
      ]
    );

    const {
      stdout: commit,
    } =
      await git(
        repoDir,
        [
          "rev-parse",
          "HEAD",
        ]
      );

    return {
      branch,
      commit:
        commit.trim(),

      url:
        `${GITHUB_WEB_REPO}/tree/${branch}`,
    };
  } finally {
    await fs.rm(
      tempRoot,
      {
        recursive: true,
        force: true,
      }
    );
  }
}
